### ISSUE TITLE
bug: latest is not the actual latest version

### ISSUE THREAD

**Issue by indaco** [nokacper24/static-templ#13]
For some reason both

```bash
go install github.com/nokacper24/static-templ@latest
go install github.com/nokacper24/static-templ@v1.0.0
```

not pull the actual latest version but the one tagged previously as `1.0.0`

I am not sure why. Are you facing the same issue?

Potentially a new `1.0.1` release and relative tag should fix.

**Comment by nokacper24** [comment]
yeah, I got the same issue.

Added new tag and a release, seems to be fine now. Realized after the fact I did not bumb the hard-coded version value in code...

**Comment by indaco** [comment]
@nokacper24 what do you think of the approach taken [here](https://github.com/indaco/static-templ/tree/version-hook)? I've implemented a super simple version management system using Git hooks:

---

a .`version` file to store the current version information. This approach replaces the need for hardcoded version strings in the codebase. Two Git hooks and a GitHub action have been added to automate version updates and ensure consistency across commits and releases.


### Key Changes

**1** **.version File**:
  - A `.version` file to store the current version of the project.
  - This file is automatically updated based on specific commit messages, ensuring the version information is always current and consistent.

**2** **Git Hooks**:
  - **commit-msg Hook**:
    - This hook is triggered when a commit message matches the pattern `chore: release v<NUMBER>`.
    - It extracts the version number from the commit message, updates the `.version file`, and stages the updated file.
  - **post-commit Hook**:
    - Ensures that the updated .`version` file is included in the commit by amending the commit if the `.version` file has been staged.
    - These hooks ensure that version updates are automatically managed during the commit process without manual intervention.
    
The `README.md` file has been updated to add a new 'Contributing' section. This section includes a short description of the usage of the hooks, which are available for both Unix-based systems and Windows.

**3** **GitHub Action**:
  - A GitHub action is set up to generate a changelog using [unjs/changelogen](https://github.com/unjs/changelogen).
  - The action ensures that the release creation process is automated with consistently formatted release notes.
  
### Release Flow

When a new release is ready to be shipped, it is as easy as:

```bash
git commit --allow-empty -m "chore: release v<NUMBER>
git tag v<NUMBER>
git push origin v<NUMBER>
```

### Prerequisites

A GitHub Personal Access Token. You can create it by using the new **Fine-grained personal access tokens** so that you can limit it to the `static-templ` repository only.

Permissions Set:

- ContentsAccess: **Read and write**
- MetadataAccess: **Read-only**

### GH_TOKEN

Create a secret in the `static-templ` repository with name = `GH_TOKEN` as it is referenced in the `.github/workflows/release.yml` file

**Comment by nokacper24** [comment]
This is great!  
Can you open a PR?  

Also, maybe we can do a separate CONTRIBUTING.md file instead?

**Comment by indaco** [comment]
Will do. Thanks 

Not sure about the updated Contributing section or a new contributing file. 

At the end, you are actually the only one who can push a new tag and create a release. 

Anyhow, I will submit the PR with the contributing section as stated above. 

Feel free to leave it there, drop it, add a new CONTRIBUTING.md file ecc.

**Comment by nokacper24** [comment]
Merged, thanks a lot! I'm having an issue though.

Looks like the `commit-msg` hook is being run twice. Not sure why this is happening.
```bash
git commit --allow-empty -m "chore: release v1.1.0"
```
the output I get is:
```
Bump version to 1.1.0.


Bump version to 1.1.0.

[main b6e3369] chore: release v1.1.0
 Date: Thu Jul 11 11:25:11 2024 +0200
 1 file changed, 1 insertion(+), 1 deletion(-)
[main 86edab5] chore: release v1.1.0
```

looking at git log the last commit is `b6e3369...`, and the previous is 0f946defd372e2b4551c0871af1f9d22b42488d8 (which is the latest one on the remote, makes sense), meaning the `86edab5` is overwritten I think, makes sense because `post-commit` hook is replacing it right? Does the `post-commit` hook maybe re-trigger the `commit-msg` hook? I am not sure how git hooks work, feel free to tell me I'm completely wrong.

**Comment by indaco** [comment]
@nokacper24 

the `--allow-empty` create a new commit

`post-hook` run `git --amend --no-edit`. it means add the `.version` file to the current commit without updating the `msg` but changing the commit hash. That is why you see the "Bump version" message twice

I think it works as expected.

If I may, I would not bump the version now. Last PRs did a bit of refactoring and add the version management. Nothing special.
If we adhere to conventional commit guidelines, those PRs are not triggering a "minor" version bump.

In addition to that, I have a couple of PRs to submit (apologies for that :) )

1.  improve code quality measurements against "goreport-card" and "golanglint-ci" (cyclomatic complexity is a bit high)
2. add a new working mode that is helping me with "vitepress-templ-preview". All preserving the current working mode as the default one

Both are already included in my [static-templ-plus](https://github.com/indaco/static-templ-plus) but, anyhow, I will submit PRs and let you decide on those.

**Comment by indaco** [comment]
I am going to submit the first PR only

If you accept the refactoring, I can submit the second one (new working mode)

It's up to you, feel free to reject

**Comment by nokacper24** [comment]
In other words, 'post-hook' does trigger the 'commit-msg' hook again... that's alright, not a big deal.

PRs are welcome! Sure, go ahead and improve code quality. I initially intended this project to just solve a problem I had, did not expect anyone to build on top of it. Apologies for cutting corners.

I don't mind adding features you need for your use case, so long they don't break my use case (which is super simple: pages built with templ components ->html files). And so far you've only improved this project! Thanks again.
