### ISSUE TITLE
proposal: version

### ISSUE THREAD

**Issue by indaco** [nokacper24/static-templ#9]
HI,
It would be useful to introduce a `version` subcommand and `git tag`.

The version command should report the `templ` version information so that users know which version of `static-templ` to use based on the templ version they have.

What do you think?

**Comment by nokacper24** [comment]
Sounds like a good idea.  
Are you able to add a tag in a PR or do i need to do it on the main branch?  

The version sub-command, I'm assuming we'd need to update information in the returned string every time templ is bumped right? Or am I missing something?

**Comment by indaco** [comment]
You should create a git tag on the main branch 

Yes, the version string should report the templ version... can get it from go.mod file. 

What do you think?

**Comment by nokacper24** [comment]
added a tag.

You can add the version command if you'd like!

**Comment by indaco** [comment]
@nokacper24 
If you approve and merge #10, I suggest:

- Deleting the `tag` you created yesterday.

Before creating a release and the new tag, I found an issue happening when run generate command I would like to fix. 

I'm going to open an issue and submit a PR to fix that. #12

By the way, if I'm bothering you feel free to tell me "stop"

Thanks

**Comment by nokacper24** [comment]
Done as you said. Thank you!

No, I'm happy you are contributing and finding this project useful. Sorry if I'm taking a little long to accept your PRs and look through code :)

**Comment by indaco** [comment]
Thanks a lot

1 day from submission to review and approval it's definitely not so much time. 

I appreciate you take your time to review my code and do your consideration.

**Comment by indaco** [comment]
@nokacper24  I think we have some issue with tags (deleting and creating again) as per #13 

Please, have a look and run your local tests
